# Generated by Django 4.0.4 on 2022-05-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAboutImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='photos/home')),
                ('image_2', models.ImageField(upload_to='photos/home')),
                ('image_3', models.ImageField(upload_to='photos/home')),
            ],
            options={
                'verbose_name': 'Home About Images',
                'verbose_name_plural': 'Home About Images',
            },
        ),
        migrations.CreateModel(
            name='HomeImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='photos/home')),
                ('video_background', models.ImageField(upload_to='photos/home')),
            ],
            options={
                'verbose_name': 'Home Images',
                'verbose_name_plural': 'Home Images',
            },
        ),
    ]
