# Generated by Django 4.0.4 on 2022-05-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_projectsimages_projects_projectstranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='slug',
            field=models.SlugField(default=False, max_length=200, unique=True, verbose_name='Slug'),
        ),
    ]
