# Generated by Django 4.0.4 on 2022-05-11 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_projects_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='more_image',
        ),
        migrations.AddField(
            model_name='projectsimages',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.projects'),
        ),
    ]
