# Generated by Django 4.0.4 on 2022-05-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_projects_date_projectstranslation_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Date'),
        ),
    ]
