# Generated by Django 4.0.4 on 2022-05-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_projects_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='date',
        ),
        migrations.RemoveField(
            model_name='projectstranslation',
            name='project_type',
        ),
        migrations.AddField(
            model_name='projects',
            name='proizvodstvo',
            field=models.BooleanField(default=False, verbose_name='proizvodstvo'),
        ),
        migrations.AddField(
            model_name='projects',
            name='projects',
            field=models.BooleanField(default=False, verbose_name='projects'),
        ),
        migrations.AddField(
            model_name='projects',
            name='uslugi',
            field=models.BooleanField(default=False, verbose_name='uslugi'),
        ),
    ]
