# Generated by Django 4.0.4 on 2022-05-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_services_alter_projectsimages_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='icon',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Icon'),
        ),
    ]
