# Generated by Django 4.0.4 on 2022-05-12 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_services_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='proizvodstvo',
            new_name='production',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='uslugi',
        ),
    ]
