# Generated by Django 4.0.4 on 2022-05-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_proizvodstvo_projects_production_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='video',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Video'),
        ),
    ]
