# Generated by Django 4.0.4 on 2022-05-19 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_homeimages_main_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeimages',
            options={'verbose_name': 'Home Video', 'verbose_name_plural': 'Home Video'},
        ),
    ]
