# Generated by Django 4.0.4 on 2022-07-20 06:30

from django.db import migrations, models
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_banner_id_alter_bannertranslation_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='site_settings/thumbnail')),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='banner',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
