# Generated by Django 4.0.4 on 2022-07-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_category_categorytranslation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='production',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='video',
        ),
        migrations.AddField(
            model_name='projects',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='photos/projects'),
        ),
        migrations.DeleteModel(
            name='ProjectsImages',
        ),
    ]
