# Generated by Django 4.0.4 on 2022-07-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_projects_production_remove_projects_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstranslation',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Type'),
        ),
    ]
