# Generated by Django 4.0.4 on 2022-07-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_projects_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='site_settings/thumbnail'),
        ),
    ]
