# Generated by Django 4.0.4 on 2022-07-22 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_sitesettings_thumbnail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
