# Generated by Django 4.0.4 on 2022-07-22 09:16

from django.db import migrations, models
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_delete_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='site_settings/thumbnail')),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
    ]
