# Generated by Django 4.0.4 on 2022-07-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
