# Generated by Django 4.0.4 on 2022-07-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_remove_sitesettings_text_sitesettingstranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='customer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Сustomer'),
        ),
    ]
