# Generated by Django 4.0.4 on 2022-07-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_services_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='customer',
        ),
        migrations.AddField(
            model_name='projects',
            name='customer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Сustomer'),
        ),
    ]
