# Generated by Django 4.0.4 on 2022-07-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_tender_tendertranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='slug',
            field=models.SlugField(default=False, max_length=200, unique=True, verbose_name='Slug'),
        ),
    ]
