# Generated by Django 4.0.4 on 2022-07-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_tender_until_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='until_hour',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Until Hour'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='until_date',
            field=models.DateField(blank=True, null=True, verbose_name='Until Date'),
        ),
    ]
