# Generated by Django 4.0.4 on 2022-07-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_tender_until_hour_alter_tender_until_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='until_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Until Date'),
        ),
    ]
