# Generated by Django 4.0.4 on 2022-07-27 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_category_options_category_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-order'], 'verbose_name': 'Navbar', 'verbose_name_plural': 'Navbar'},
        ),
    ]
