# Generated by Django 3.2 on 2022-07-28 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Navbar', 'verbose_name_plural': 'Navbar'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
    ]
