# Generated by Django 3.2 on 2022-07-28 07:50

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/home', verbose_name='Image')),
                ('experience', models.CharField(max_length=245, verbose_name='Experience')),
            ],
            options={
                'verbose_name': 'Home About Images',
                'verbose_name_plural': 'Home About Images',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AboutTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=245, verbose_name='Title')),
                ('short_description', models.CharField(max_length=300, verbose_name='Short Description')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.about')),
            ],
            options={
                'verbose_name': 'Home About Images Translation',
                'db_table': 'main_about_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='HomeAboutImages',
        ),
    ]
