# Generated by Django 3.2 on 2022-07-28 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_auto_20220728_0750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About', 'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='abouttranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'About Translation'},
        ),
    ]
