# Generated by Django 3.2 on 2022-07-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_auto_20220728_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouttranslation',
            name='short_description',
            field=models.CharField(max_length=1300, verbose_name='Short Description'),
        ),
    ]
