# Generated by Django 3.2 on 2022-08-09 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_auto_20220804_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticcontent',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Category'),
        ),
    ]
