# Generated by Django 3.2 on 2022-08-25 09:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_staticcontent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiptranslation',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Description'),
        ),
    ]
