# Generated by Django 3.2 on 2022-08-25 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_auto_20220825_0958'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeImages',
        ),
    ]
