# Generated by Django 4.1.4 on 2022-12-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_blog_location_blogtranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=20)),
                ('created_add', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Visit',
            },
        ),
    ]
